[package]
name = "tl_casper"
version = "0.1.0"
authors = ["Nicolas Huguenin <nichuguen@gmail.com>"]

[dependencies]


[lib]
name = "tl_casper"
path = "src/lib.rs"

[[bin]]
name = "main"
path = "src/main.rs"
